TP2_Gabriel_Lavoie_1148/Models/Livres.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;

namespace TP2_Gabriel_Lavoie.Models
{
    public class Livres
    {
        public int Id { get; set; }
        [DisplayName("Titre du Livre")]
        public string Titre { get; set; }
        [DisplayName("Nom de l'auteur")]
        public string Auteur { get; set; }
        [DisplayName("Categorie du livre")]
        public string Categorie { get; set; }

    }
}

TP2_Gabriel_Lavoie_1148/Models/Membres.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;

namespace TP2_Gabriel_Lavoie.Models
{
    public class Membres
    {
        public int Id { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public string Courriel { get; set; }
        public string Telephone { get; set; }

    }
}

TP2_Gabriel_Lavoie_1148/Models/Pret.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP2_Gabriel_Lavoie.Models
{
    public class Pret
    {
        public int Id { get; set; }
        public int IdLivres { get; set; }
        public int IdMembres { get; set;}
        public DateTime Date { get; set; }

        public bool EstRetard()
        {
            if (DateTime.Now >= Date.AddDays(7))
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
}

TP2_Gabriel_Lavoie_1148/Models/Retard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP2_Gabriel_Lavoie.Models
{
    public class Retard
    {
        public int Id { get; set; }
        public int IdLivres { get; set; }
        public int IdMembres { get; set; }
        public int IdPret { get; set; }
        public DateTime Date { get; set; }
        
        public Retard() { }
        public Retard(int id, int idLivre, int idMembre, int idPret, DateTime date)
        {
            Id = id;
            IdLivres = idLivre;
            IdMembres = idMembre;
            IdPret = idPret;
            Date = date;
        }
    }
}

TP2_Gabriel_Lavoie_1148/Controllers/LivresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP2_Gabriel_Lavoie.Models;

namespace TP2_Gabriel_Lavoie.Controllers
{
    public class LivresController : Controller
    {
        string chaineConnexion = @"Data Source=(LocalDb)\ProjectModels;Initial Catalog=bdgplcc; Integrated Security =true";

        // GET: Livres
        public ActionResult CollectionLivres()
        {
            DataTable tabLivres= new DataTable();
            using(SqlConnection connexion = new SqlConnection(chaineConnexion))
            {
                connexion.Open();
                SqlDataAdapter adapter= new SqlDataAdapter("SELECT * FROM Livres", connexion);
                adapter.Fill(tabLivres);
            }
            return View(tabLivres);
        }

        // GET: Livres
        public ActionResult Acceuil()
        {
            return View();
        }

        // GET: Livres
       
       
        // GET: Livres/Create
        public ActionResult CreateLivres()
        {
            return View(new Livres());
        }

        // POST: Livres/Create
        [HttpPost]
        public ActionResult CreateLivres(Livres livre)
        {
            try
            {
                using (SqlConnection connexion = new SqlConnection(chaineConnexion))
                {
                    connexion.Open();
                    string requete = "INSERT INTO livres VALUES(@Titre,@Auteur,@Categorie)";
                    SqlCommand command = new SqlCommand(requete, connexion);
                    command.Parameters.AddWithValue("@Titre", livre.Titre);
                    command.Parameters.AddWithValue("@Auteur", livre.Auteur);
                    command.Parameters.AddWithValue("@Categorie", livre.Categorie);
                    command.ExecuteNonQuery();
                }

                return RedirectToAction("Acceuil");
            }
            catch
            {
                return View();
            }
        }
        // GET: Livres/Edit/5
        public ActionResult EditLivre(int id)
        {
            Livres livre = new Livres();
            DataTable tabLivres = new DataTable();
            using (SqlConnection connexion = new SqlConnection(chaineConnexion))
            {
                connexion.Open();
                string requete = "SELECT * FROM livres WHERE Id =@Id";
                SqlDataAdapter adapter = new SqlDataAdapter(requete, connexion);
                adapter.SelectCommand.Parameters.AddWithValue("@Id", id);
                adapter.Fill(tabLivres);
            }
            if (tabLivres.Rows.Count == 1)
            {
                livre.Id = Convert.ToInt32(tabLivres.Rows[0][0].ToString());
                livre.Titre = tabLivres.Rows[0][1].ToString();
                livre.Auteur = tabLivres.Rows[0][2].ToString();
                livre.Categorie = tabLivres.Rows[0][3].ToString();
                return View(livre);
            }
            else
            {
                return RedirectToAction("Acceuil");
            }
        }

        // POST: Livres/Edit/5
        [HttpPost]
        public ActionResult EditLivre(Livres livre)
        {
            try
            {
                using (SqlConnection connexion = new SqlConnection(chaineConnexion))
                {
                    connexion.Open();
                    string requete = "UPDATE livres SET Titre=@Titre, Auteur=@Auteur, Categorie=@Categorie WHERE Id=@Id";
                    SqlCommand command = new SqlCommand(requete, connexion);
                    command.Parameters.AddWithValue("@Id", livre.Id);
                    command.Parameters.AddWithValue("@Titre", livre.Titre);
                    command.Parameters.AddWithValue("@Auteur", livre.Auteur);
                    command.Parameters.AddWithValue("@Categorie", livre.Categorie);
                    command.ExecuteNonQuery();
                }

                return RedirectToAction("CollectionLivres");
            }
            catch
            {
                return View();
            }
        }

        // GET: Livres/Delete/5
        public ActionResult DeleteLivre(int id)
        {
            return View();
        }

        // POST: Livres/Delete/5
        [HttpPost]
        public ActionResult DeleteLivre(int id, FormCollection collection)
        {
            try
            {
                using (SqlConnection connexion = new SqlConnection(chaineConnexion))
                {
                    connexion.Open();
                    string requete = "DELETE FROM livres WHERE Id=@Id";
                    SqlCommand command = new SqlCommand(requete, connexion);
                    command.Parameters.AddWithValue("@Id", id);
                    command.ExecuteNonQuery();
                }
                return RedirectToAction("CollectionLivres");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Membres()
        {
            DataTable tabMembres = new DataTable();
            using (SqlConnection connexion = new SqlConnection(chaineConnexion))
            {
                connexion.Open();
                SqlDataAdapter adapter = new SqlDataAdapter("SELECT * FROM membres", connexion);
                adapter.Fill(tabMembres);
            }
            return View(tabMembres);
        }

        // GET: Livres/Create
        public ActionResult CreateMembres()
        {
            return View(new Membres());
        }

        // POST: Livres/Create
        [HttpPost]
        public ActionResult CreateMembres(Membres membres)
        {
            try
            {
                using (SqlConnection connexion = new SqlConnection(chaineConnexion))
                {
                    connexion.Open();
                    string requete = "INSERT INTO membres VALUES(@Prenom, @Nom, @Courriel, @Telephone)";
                    SqlCommand command = new SqlCommand(requete, connexion);
                    command.Parameters.AddWithValue("@Prenom", membres.Prenom);
                    command.Parameters.AddWithValue("@Nom", membres.Nom);
                    command.Parameters.AddWithValue("@Courriel", membres.Courriel);
                    command.Parameters.AddWithValue("@Telephone", membres.Telephone);
                    command.ExecuteNonQuery();
                }

                return RedirectToAction("Acceuil");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult EditMembres(int id)
        {
            Membres membres = new Membres();
            DataTable tabMembre = new DataTable();
            using (SqlConnection connexion = new SqlConnection(chaineConnexion))
            {
                connexion.Open();
                string requete = "SELECT * FROM membres WHERE Id =@Id";
                SqlDataAdapter adapter = new SqlDataAdapter(requete, connexion);
                adapter.SelectCommand.Parameters.AddWithValue("@Id", id);
                adapter.Fill(tabMembre);
            }
            if (tabMembre.Rows.Count == 1)
            {
                membres.Id = Convert.ToInt32(tabMembre.Rows[0][0].ToString());
                membres.Prenom = tabMembre.Rows[0][1].ToString();
                membres.Nom = tabMembre.Rows[0][2].ToString();
                membres.Courriel = tabMembre.Rows[0][3].ToString();
                membres.Telephone = tabMembre.Rows[0][4].ToString();
                return View(membres);
            }
            else
            {
                return RedirectToAction("Acceuil");
            }
        }

        // POST: Livres/Edit/5
        [HttpPost]
        public ActionResult EditMembres(Membres membres)
        {
            try
            {
                using (SqlConnection connexion = new SqlConnection(chaineConnexion))
                {
                    connexion.Open();
                    string requete = "UPDATE membres SET Prenom=@Prenom, Nom=@Nom, Courriel=@Courriel WHERE Id=@Id";
                    SqlCommand command = new SqlCommand(requete, connexion);
                    command.Parameters.AddWithValue("@Id", membres.Id);
                    command.Parameters.AddWithValue("@Prenom", membres.Prenom);
                    command.Parameters.AddWithValue("@Nom", membres.Nom);
                    command.Parameters.AddWithValue("@Courriel", membres.Courriel);
                    command.Parameters.AddWithValue("@Telephone", membres.Telephone);
                    command.ExecuteNonQuery();
                }

                return RedirectToAction("Membres");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult DeleteMembres(int id)
        {
            return View();
        }

        // POST: Livres/Delete/5
        [HttpPost]
        public ActionResult DeleteMembres(int id, FormCollection collection)
        {
            try
            {
                using (SqlConnection connexion = new SqlConnection(chaineConnexion))
                {
                    connexion.Open();
                    string requete = "DELETE FROM membres WHERE Id=@Id";
                    SqlCommand command = new SqlCommand(requete, connexion);
                    command.Parameters.AddWithValue("@Id", id);
                    command.ExecuteNonQuery();
                }
                return RedirectToAction("Membres");
            }
            catch
            {
                return View();
            }
        }

        // GET: Livres
        public ActionResult Pret()
        {
            DataTable tabPret = new DataTable();
            using (SqlConnection connexion = new SqlConnection(chaineConnexion))
            {
                connexion.Open();

TP2_Gabriel_Lavoie_1148/Views/Livres/Acceuil.cshtml
@{
    ViewBag.Title = "Acceuil";
}

<h2 class="titre">Biblioth&egrave;que Lavoie</h2>
<h4 class="titre">Une biblio qui vous guidera vers le bon chemin</h4>

<p> 
    Le centre communautaire de St-Ishrinka est la pour le d&eacute;veloppement de vos connaissances. 
    Si vous voulez emprunter un livre de tout genre, vous devez devenir membre du centre. 
    Pour ce faire, vous devez venir en personne cr&eacute;er votre abonnement.
    Les membres peuvent emprunter jusqu&apos;&agrave; <u>trois</u> livres pour une dur&eacute;e maximale de <u>7</u> jours.
    Les pr&ecirc;ts sont <u>gratuits</u>, mais s&apos;il y a retard, des frais seront engendr&eacute;.
</p>

TP2_Gabriel_Lavoie_1148/Views/Livres/CollectionLivres.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "CollectionLivres";
}

<h2>Collection de livre</h2>
<br />
<p><a href="@Url.Action("CreateLivres", "Livres")">Ajouter un livre &agrave; la collection</a></p>
<br />

<table class="table  table-hover table-striped">
    <thead>
        <tr>
            <th scope="col">Id du Livre</th>
            <th scope="col">Titre</th>
            <th scope="col">Auteur</th>
            <th scope="col">Categorie</th>
            <th scope="col">Modifier</th>
            <th scope="col">Suprimer</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Rows.Count; i++)
        {
            <tr>
                <td>@Model.Rows[i][0]</td>
                <td>@Model.Rows[i][1]</td>
                <td>@Model.Rows[i][2]</td>
                <td>@Model.Rows[i][3]</td>
                <td>
                    <a href="@Url.Action("EditLivre", "Livres", new { @id = Model.Rows[i][0]})"><img src="~/Content/Image/Modifier.png" alt="Modifier" width="10" height="10" /></a>
                </td>
                <td>
                    <a href="@Url.Action("DeleteLivre", "Livres", new { @id = Model.Rows[i][0]})"><img src="~/Content/Image/Suprimer.png" alt="Suprimer" width="10" height="10" /></a>
                </td>
            </tr>
        }
    </tbody>
</table>

TP2_Gabriel_Lavoie_1148/Views/Livres/CreateLivres.cshtml
@model TP2_Gabriel_Lavoie.Models.Livres

@{
    ViewBag.Title = "CreateLivres";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Ajouter un livre dans la collection</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Titre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Titre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Titre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Auteur, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Auteur, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Auteur, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Categorie, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Categorie, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Categorie, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default btn-outline-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "CollectionLivres")
</div>

TP2_Gabriel_Lavoie_1148/Views/Livres/CreateMembres.cshtml
@model TP2_Gabriel_Lavoie.Models.Membres

@{
    ViewBag.Title = "CreateMembre";
}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ajouter un nouveau membres</h4>
        <p>Veuillez ajoutez les informations ci-dessous</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Prenom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prenom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prenom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Courriel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Courriel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Courriel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default btn-outline-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Membres")
</div>

TP2_Gabriel_Lavoie_1148/Views/Livres/CreatePret.cshtml
@model TP2_Gabriel_Lavoie.Models.Pret

@{
    ViewBag.Title = "CreatePret";
}

<h2>Cr&eacute;er</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Pr&ecirc;t</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.IdLivres, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdLivres, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdLivres, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IdLivres, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdLivres, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdLivres, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IdLivres, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdLivres, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdLivres, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IdMembres, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdMembres, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdMembres, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default btn-outline-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Pret")
</div>

TP2_Gabriel_Lavoie_1148/Views/Livres/DeleteLivre.cshtml
@model TP2_Gabriel_Lavoie.Models.Livres

@{
    ViewBag.Title = "DeleteLivre";
}

<h3>Etes-vous sur de vouloir suprimer ce livre?</h3>
<div>
    <hr />
    

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default btn-danger" /> |
            @Html.ActionLink("Non", "CollectionLivres")
        </div>
    }
</div>

TP2_Gabriel_Lavoie_1148/Views/Livres/DeleteMembres.cshtml
@model TP2_Gabriel_Lavoie.Models.Membres

@{
    ViewBag.Title = "DeleteMembres";
}

<h3>Etes-vous sur de vouloir suprimer ce membre?</h3>
<div>
   <hr/>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TP2_Gabriel_Lavoie_1148/Views/Livres/DeletePret.cshtml
@model TP2_Gabriel_Lavoie.Models.Pret

@{
    ViewBag.Title = "DeletePret";
}

<h2>DeletePret</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pret</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdLivres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdLivres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdMembres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdMembres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default btn-danger" /> |
            @Html.ActionLink("Back to List", "Pret")
        </div>
    }
</div>

TP2_Gabriel_Lavoie_1148/Views/Livres/EditLivre.cshtml
@model TP2_Gabriel_Lavoie.Models.Livres

@{
    ViewBag.Title = "EditLivre";
}

<h2>Modifier</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Livres</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Titre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Auteur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Auteur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Auteur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Categorie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categorie, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default btn-outline-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CollectionLivres")
</div>

TP2_Gabriel_Lavoie_1148/Views/Livres/Membres.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "Membres";
}

<h2>Liste des Membres</h2>
<br />
<p><a href="@Url.Action("CreateMembres", "Livres")">Ajouter un nouveau membre</a></p>
<br />

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Prenom</th>
            <th scope="col">Nom</th>
            <th scope="col">Courriel</th>
            <th scope="col">Telephone</th>
            <th scope="col">Modifier</th>
            <th scope="col">Suprimer</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Rows.Count; i++)
        {
            <tr>
                <td>@Model.Rows[i][0]</td>
                <td>@Model.Rows[i][1]</td>
                <td>@Model.Rows[i][2]</td>
                <td>@Model.Rows[i][3]</td>
                <td>@Model.Rows[i][4]</td>
                <td>
                    <a href="@Url.Action("EditMembres", "Livres", new { @id = Model.Rows[i][0]})"><img src="~/Content/Image/Modifier.png" alt="Modifier" width="10" height="10" /></a>
                </td>
                <td>
                    <a href="@Url.Action("DeleteMembres", "Livres", new { @id = Model.Rows[i][0]})"><img src="~/Content/Image/Suprimer.png" alt="Suprimer" width="10" height="10" /></a>
                </td>
            </tr>
        }
    </tbody>
</table>

TP2_Gabriel_Lavoie_1148/Views/Livres/Pret.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "Membres";
}

<h2>Pr&ecirc;t </h2>
<br />
<p><a href="@Url.Action("CreatePret", "Livres")">Faire un pret</a></p>
<br />

<table class="table  table-hover table-striped">
    <thead>
        <tr>
            <th scope="col">Id du pr&ecirc;t</th>
            <th scope="col">Id du livre</th>
            <th scope="col">Id du membre</th>
            <th scope="col">Date du pret</th>
            <th scope="col">Suprimer</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Rows.Count; i++)
         {
            <tr>
                <td>@Model.Rows[i][0]</td>
                <td>@Model.Rows[i][1]</td>
                <td>@Model.Rows[i][2]</td>
                <td>@Model.Rows[i][3]</td>
                <td>
                    <a href="@Url.Action("DeletePret", "Livres", new { @id = Model.Rows[i][0]})"><img src="~/Content/Image/Suprimer.png" alt="Suprimer" width="10" height="10" /></a>
                </td>
            </tr>
         }
    </tbody>
</table>

TP2_Gabriel_Lavoie_1148/Views/Livres/Retard.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "Membres";
}

<h2>Retard</h2>

<table class="table  table-hover table-striped">
    <thead>
        <tr>
            <th scope="col">Id du retard</th>
            <th scope="col">Id du livre</th>
            <th scope="col">Id du membre</th>
            <th scope="col">Id du pr&ecirc;t</th>
            <th scope="col">Date du retard</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Rows.Count; i++)
        {
            <tr>
                <td>@Model.Rows[i][0]</td>
                <td>@Model.Rows[i][1]</td>
                <td>@Model.Rows[i][2]</td>
                <td>@Model.Rows[i][3]</td>
                <td>@Model.Rows[i][4]</td>
            </tr>
        }
    </tbody>
</table>